apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world-service
  template:
    metadata:
      labels:
        app: world-service
    spec:
      containers:
      - name: world-service
        image: jainamchhatbar/world-service:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: world-service
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001
  selector:
    app: world-service
